### ISSUE TITLE
Would it be possible to change the print tray destination?

### ISSUE THREAD

**Issue by jordancox7483** [evilhawk00/PrintheadMaintainer#1]
My printer has a rear feed and I would like to throw old paper that has already been used in the rear feed for use by the print maintainer.    Would it be possible to change the script to use a specific tray?  Right now it just seems to use the default main tray - I tried setting the windows printer default to the rear tray but that didn't change how this printed.  

Also, thank you for this - I love it and needed it.

**Comment by evilhawk00** [comment]
Theoretically it is possible to add something like this with code, unfortunately this thing is complicated, without testing with a real machine that has more than one paper tray, I don't think I can create a stable, reliable code for this. I'm using Epson personal printer that only has one paper tray, I don't own a commercial printer that has more than one paper tray.

However, I believe there's always someone else can finish this, so that's why I shared my source code with the whole world. Hoping someone else can find this project, fork and make enhancements. So I'm going to leave some hint I know here, hoping someone else owns a commercial printer can finish this. (Or maybe in the future I own a commercial printer, and it's not highly possible)

AFAIK, this can be done by changing the C++ function in the service
`int intSendPrintBmpJobToPrinter(const std::wstring &wsDocumentNameToDisplayInQueue, const std::wstring &wsBmpFilePath, const std::wstring &wsPrinterName)` in the file [PrinterUtils.cpp](https://github.com/evilhawk00/PrintheadMaintainer/blob/main/PrintheadMaintainerService/PrintheadMaintainer/Utils/PrinterUtils.cpp)

There's one line `HDC PrinterDC = CreateDC(L"WINSPOOL", lpPrinterName, NULL, NULL);`, the last NULL changes to `DEVMODE` structure pointer, according to the [MSDN document of CreateDC](https://learn.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-createdcw). Set the `dmDefaultSource` property in DEVMODE structure according to the [MSDN document of DEVMODE](https://learn.microsoft.com/en-us/windows/win32/api/wingdi/ns-wingdi-devmodea?redirectedfrom=MSDN). This can change the paper tray source if my understanding is correct.

Then, to add a UI for changing paper tray, change the C# file [SettingsView.xaml](https://github.com/evilhawk00/PrintheadMaintainer/blob/main/PrintheadMaintainerUI/Views/SettingsView.xaml) and [SettingsViewModel.cs](https://github.com/evilhawk00/PrintheadMaintainer/blob/main/PrintheadMaintainerUI/ViewModels/SettingsViewModel.cs)

Let's hope someone can find this :)

**Comment by jordancox7483** [comment]
Thank you for the response.  I've never done anything in C++ but now I'm curious if I could figure it out so I'm going to poke around.  I'll let you know if I get it to work but I probably will just end up failing.
